spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Magjan/config-repo
          default-label: main
          timeout: 5000
          clone-on-start: true
          force-pull: true